### ISSUE TITLE
[Bug] Unusable in Arabic documents

### ISSUE THREAD

**Issue by amarakon** [michal-h21/linebreaker#6]
First, thanks for such a useful LaTeX package. But unfortunately, I cannot use it on my Arabic documents because it causes two problems:

1. Paragraphs are typeset from left to right, instead of from right to left.
2. The Arabic letters look detached and glitchy.

Here is a minimum working example you can use to test it:

```tex
\documentclass{article}

\usepackage{linebreaker}
\usepackage[bidi = basic]{babel}
\babelprovide[main]{arabic}
\babelfont{rm}{Scheherazade New}

\begin{document}
لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.
\end{document}
```

<img src="https://user-images.githubusercontent.com/92645199/223087007-79459c32-fa61-47ee-b837-9cc1d2f8f428.png" width="100%" />

**Comment by hpvd** [comment]
just an addition for when trying to produce:
Scheherazade New is available at:
https://software.sil.org/scheherazade/

**Comment by hpvd** [comment]
comparison (latest Miktex, Windows, font installed as ttf)
![2023-03-06_12h02_43](https://user-images.githubusercontent.com/5681880/223093775-0569cabd-1a4b-41e1-96f7-51f90bd2e350.png)

@amarakon is this screenshot of "without the package" looking the way you would rate it as good? (sorry, I have no experience how arabic should look like)

**Comment by hpvd** [comment]
just for anyone intersted in a quick auto-translation:
But I must point out to you that all this misconception about denouncing pleasure and glorifying pain
It has already arisen, and I will show you the details so that you may discover the truth and basis of that human happiness, for there is no one else
He rejects, hates, or avoids feeling happy, but thanks to those people who don't realize that
Happiness must be felt in a more rational and logical way, and this exposes them to face the circumstances
Painful, and I repeat that there is no one who desires love and attainment and takes pleasure in pain, pain is pain
But as a result of circumstances happiness may lie in the toil and sorrow we endure.

**Comment by michal-h21** [comment]
Thanks for the report. The paragraph direction is lost, which causes both issues. Hopefully, the last commit should fix this issue.

**Comment by hpvd** [comment]
wow, fast as always.
If @amarakon confirms everything looking fine now,
-> maybe it's a good reason for a new release to ctan?
The last one was one year ago...
https://ctan.org/pkg/linebreaker

**Comment by michal-h21** [comment]
Yes, I should make an update if everything works. This is a serious issue.

**Comment by hpvd** [comment]
btw @amarako
having you in this discussion is a rare chance.
-> Would you mind giving the combination of
- this linebreaker package 
- with the lua-widow-control package
a try for an Arabic document?
And report if everything looks fine to you?
Would be awesome!

Background: since both packages are complementing each other in a perfect way, they are often used together

see https://github.com/gucci-on-fleek/lua-widow-control

**Comment by amarakon** [comment]
> @amarakon is this screenshot of "without the package" looking the way you would rate it as good? (sorry, I have no experience how arabic should look like)

Yes, that looks perfect. Thanks for such a quick fix!

> wow, fast as always.
If @amarakon confirms everything looking fine now,
-> maybe it's a good reason for a new release to ctan?
The last one was one year ago...
https://ctan.org/pkg/linebreaker

I agree, I think this is a good idea.

> -> Would you mind giving the combination of
- this linebreaker package
- with the lua-widow-control package
>
> a try for an **Arabic document**?

I tried both of them together, and they both work as expected. `linebreaker` prevents overfull lines, and `lua-widow-control` prevents widows and orphans.

**Comment by hpvd** [comment]
many thanks!

**Comment by hpvd** [comment]
@michal-h21 thanks for new release on ctan!
